%global debug_package %{nil}
%global _build_id_links none
%global __strip /bin/true
%global __jar_repack %{nil}

# Do not verity tarball signatures
%bcond_with verify

# get english only and no-langpacks for a faster smoketest build
# fedpkg compile/install/local/mockbuild does not handle --without ATM,
# so it is necessary to change this to bcond_with to achieve the same
# effect
%bcond_without langpacks

# generated by %%langpack definitions
%global langpack_langs %{nil}

%global symbolic_commit cf9949d6e64e819eef0f2f1904a5519b34036289
%global symbolic_url https://gitlab.gnome.org/Teams/Design/symbolic-app-icons/-/raw/%{symbolic_commit}/symbolic/legacy

%global ver     %%{lua:ver = string.gsub(rpm.expand("%{version}"), "~", "."); print(ver)}
%global verpre %%(echo %%{ver} | cut -s -d. -f5)
%global verurl %%(echo %%{ver} | cut -d. -f1-3)
%global verprod %%(echo %%{ver} | cut -d. -f1-2)

Summary:        Free Software Productivity Suite
Name:           libreoffice
Epoch:          2
# If rc, use "~" instead ".", as ~rc
Version:        7.5.3.2
Release:        100%{?dist}

# default new files are: MPLv2
# older files are typically: MPLv2 incorporating work under ASLv2
# nlpsolver is: LGPLv3
# icon-themes/karasa_jaga/COPYING: LGPLv3+
# icon-themes/colibre/COPYING-ICONS: CC0
# lotuswordpro is: Either LGPL 2.1 or SISSL 1.1
# wizards/source/access2base: Either MPLv2 or LGPLv3+
# writerperfect/source/common/DirectoryStream.cxx: MPLv2 or LGPLv2+
# extras/source/autocorr/lang/hr/license.md: GPL 2.0 or LGPL2 or MPLv1.1
# odk/examples/java/...: 3 clause BSD
License:        MPL-2.0 AND Apache-2.0 AND LGPL-3.0-only AND LGPL-3.0-or-later AND CC0-1.0 AND BSD-3-Clause AND (LGPL-2.1-only OR SISSL) AND (MPL-2.0 OR LGPL-3.0-or-later) AND (MPL-2.0 OR LGPL-2.1-or-later) AND (MPL-1.1 OR GPL-2.0-only OR LGPL-2.1-only)
URL:            http://www.libreoffice.org/

%if "%{verpre}"
%global libo_channel testing
%global verpkg %{ver}
%else
%global libo_channel stable
%global verpkg %{verurl}
%endif

%global source_url http://download.documentfoundation.org/%{name}/%{libo_channel}/%%{verurl}/rpm/%{_arch}

# signatures as odd numbers
Source0:        %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm.tar.gz
Source1:        %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm.tar.gz.asc
Source2:        %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_sdk.tar.gz
Source3:        %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_sdk.tar.gz.asc
Source4:        %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_en-US.tar.gz
Source5:        %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_en-US.tar.gz.asc
Source6:        gpgkey-C2839ECAD9408FBE9531C3E9F434A1EFAFEEAEA3.gpg.asc
Source7:        %{name}-extension-manager.desktop
Source8:        %{name}-multiliblauncher.sh
Source9:        %{name}.1
Source10:       unopkg.1

# symbolic icons
Source42:       %{symbolic_url}/libreoffice-base-symbolic.svg
Source43:       %{symbolic_url}/libreoffice-calc-symbolic.svg
Source44:       %{symbolic_url}/libreoffice-draw-symbolic.svg
Source45:       %{symbolic_url}/libreoffice-impress-symbolic.svg
Source46:       %{symbolic_url}/libreoffice-main-symbolic.svg
Source47:       %{symbolic_url}/libreoffice-math-symbolic.svg
Source48:       %{symbolic_url}/libreoffice-writer-symbolic.svg

# Language packs
%if %{with langpacks}
Source200:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_af.tar.gz
Source201:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_af.tar.gz.asc
Source202:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ar.tar.gz
Source203:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ar.tar.gz.asc
Source204:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ar.tar.gz
Source205:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ar.tar.gz.asc
Source206:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_as.tar.gz
Source207:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_as.tar.gz.asc
Source208:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_bg.tar.gz
Source209:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_bg.tar.gz.asc
Source210:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_bg.tar.gz
Source211:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_bg.tar.gz.asc
Source212:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_bn.tar.gz
Source213:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_bn.tar.gz.asc
Source214:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_bn.tar.gz
Source215:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_bn.tar.gz.asc
Source216:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_br.tar.gz
Source217:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_br.tar.gz.asc
Source218:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ca.tar.gz
Source219:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ca.tar.gz.asc
Source220:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ca.tar.gz
Source221:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ca.tar.gz.asc
Source222:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_cs.tar.gz
Source223:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_cs.tar.gz.asc
Source224:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_cs.tar.gz
Source225:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_cs.tar.gz.asc
Source226:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_cy.tar.gz
Source227:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_cy.tar.gz.asc
Source228:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_da.tar.gz
Source229:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_da.tar.gz.asc
Source230:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_da.tar.gz
Source231:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_da.tar.gz.asc
Source232:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_de.tar.gz
Source233:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_de.tar.gz.asc
Source234:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_de.tar.gz
Source235:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_de.tar.gz.asc
Source236:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_dz.tar.gz
Source237:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_dz.tar.gz.asc
Source238:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_dz.tar.gz
Source239:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_dz.tar.gz.asc
Source240:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_el.tar.gz
Source241:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_el.tar.gz.asc
Source242:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_el.tar.gz
Source243:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_el.tar.gz.asc
Source244:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_eo.tar.gz
Source245:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_eo.tar.gz.asc
Source246:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_eo.tar.gz
Source247:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_eo.tar.gz.asc
Source248:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_es.tar.gz
Source249:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_es.tar.gz.asc
Source250:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_es.tar.gz
Source251:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_es.tar.gz.asc
Source252:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_et.tar.gz
Source253:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_et.tar.gz.asc
Source254:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_et.tar.gz
Source255:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_et.tar.gz.asc
Source256:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_eu.tar.gz
Source257:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_eu.tar.gz.asc
Source258:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_eu.tar.gz
Source259:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_eu.tar.gz.asc
Source260:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fa.tar.gz
Source261:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fa.tar.gz.asc
Source262:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_fi.tar.gz
Source263:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_fi.tar.gz.asc
Source264:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fi.tar.gz
Source265:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fi.tar.gz.asc
Source266:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_fr.tar.gz
Source267:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_fr.tar.gz.asc
Source268:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fr.tar.gz
Source269:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fr.tar.gz.asc
Source270:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fy.tar.gz
Source271:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_fy.tar.gz.asc
Source272:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ga.tar.gz
Source273:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ga.tar.gz.asc
Source274:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_gl.tar.gz
Source275:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_gl.tar.gz.asc
Source276:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_gl.tar.gz
Source277:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_gl.tar.gz.asc
Source278:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_gu.tar.gz
Source279:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_gu.tar.gz.asc
Source280:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_gu.tar.gz
Source281:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_gu.tar.gz.asc
Source282:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_he.tar.gz
Source283:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_he.tar.gz.asc
Source284:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_he.tar.gz
Source285:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_he.tar.gz.asc
Source286:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_hi.tar.gz
Source287:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_hi.tar.gz.asc
Source288:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_hi.tar.gz
Source289:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_hi.tar.gz.asc
Source290:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_hr.tar.gz
Source291:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_hr.tar.gz.asc
Source292:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_hr.tar.gz
Source293:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_hr.tar.gz.asc
Source294:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_hu.tar.gz
Source295:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_hu.tar.gz.asc
Source296:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_hu.tar.gz
Source297:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_hu.tar.gz.asc
Source298:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_id.tar.gz
Source299:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_id.tar.gz.asc
Source300:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_id.tar.gz
Source301:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_id.tar.gz.asc
Source302:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_it.tar.gz
Source303:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_it.tar.gz.asc
Source304:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_it.tar.gz
Source305:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_it.tar.gz.asc
Source306:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ja.tar.gz
Source307:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ja.tar.gz.asc
Source308:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ja.tar.gz
Source309:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ja.tar.gz.asc
Source310:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_kk.tar.gz
Source311:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_kk.tar.gz.asc
Source312:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_kn.tar.gz
Source313:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_kn.tar.gz.asc
Source314:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ko.tar.gz
Source315:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ko.tar.gz.asc
Source316:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ko.tar.gz
Source317:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ko.tar.gz.asc
Source318:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_lt.tar.gz
Source319:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_lt.tar.gz.asc
Source320:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_lt.tar.gz
Source321:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_lt.tar.gz.asc
Source322:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_lv.tar.gz
Source323:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_lv.tar.gz.asc
Source324:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_lv.tar.gz
Source325:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_lv.tar.gz.asc
Source326:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_mai.tar.gz
Source327:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_mai.tar.gz.asc
Source328:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ml.tar.gz
Source329:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ml.tar.gz.asc
Source330:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_mr.tar.gz
Source331:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_mr.tar.gz.asc
Source332:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_nb.tar.gz
Source333:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_nb.tar.gz.asc
Source334:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nb.tar.gz
Source335:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nb.tar.gz.asc
Source336:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_nl.tar.gz
Source337:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_nl.tar.gz.asc
Source338:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nl.tar.gz
Source339:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nl.tar.gz.asc
Source340:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_nn.tar.gz
Source341:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_nn.tar.gz.asc
Source342:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nn.tar.gz
Source343:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nn.tar.gz.asc
Source344:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nr.tar.gz
Source345:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nr.tar.gz.asc
Source346:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nso.tar.gz
Source347:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_nso.tar.gz.asc
Source348:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_or.tar.gz
Source349:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_or.tar.gz.asc
Source350:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pa-IN.tar.gz
Source351:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pa-IN.tar.gz.asc
Source352:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_pl.tar.gz
Source353:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_pl.tar.gz.asc
Source354:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pl.tar.gz
Source355:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pl.tar.gz.asc
Source356:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_pt-BR.tar.gz
Source357:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_pt-BR.tar.gz.asc
Source358:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pt-BR.tar.gz
Source359:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pt-BR.tar.gz.asc
Source360:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_pt.tar.gz
Source361:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_pt.tar.gz.asc
Source362:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pt.tar.gz
Source363:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_pt.tar.gz.asc
Source364:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ro.tar.gz
Source365:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ro.tar.gz.asc
Source366:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ro.tar.gz
Source367:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ro.tar.gz.asc
Source368:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ru.tar.gz
Source369:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ru.tar.gz.asc
Source370:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ru.tar.gz
Source371:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ru.tar.gz.asc
Source372:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_si.tar.gz
Source373:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_si.tar.gz.asc
Source374:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_si.tar.gz
Source375:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_si.tar.gz.asc
Source376:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_sk.tar.gz
Source377:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_sk.tar.gz.asc
Source378:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sk.tar.gz
Source379:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sk.tar.gz.asc
Source380:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_sl.tar.gz
Source381:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_sl.tar.gz.asc
Source382:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sl.tar.gz
Source383:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sl.tar.gz.asc
Source384:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sr.tar.gz
Source385:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sr.tar.gz.asc
Source386:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sr-Latn.tar.gz
Source387:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sr-Latn.tar.gz.asc
Source388:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ss.tar.gz
Source389:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ss.tar.gz.asc
Source390:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_st.tar.gz
Source391:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_st.tar.gz.asc
Source392:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_sv.tar.gz
Source393:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_sv.tar.gz.asc
Source394:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sv.tar.gz
Source395:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_sv.tar.gz.asc
Source396:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ta.tar.gz
Source397:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_ta.tar.gz.asc
Source398:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ta.tar.gz
Source399:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ta.tar.gz.asc
Source400:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_te.tar.gz
Source401:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_te.tar.gz.asc
Source402:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_th.tar.gz
Source403:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_th.tar.gz.asc
Source404:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_tn.tar.gz
Source405:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_tn.tar.gz.asc
Source406:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_tr.tar.gz
Source407:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_tr.tar.gz.asc
Source408:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_tr.tar.gz
Source409:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_tr.tar.gz.asc
Source410:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ts.tar.gz
Source411:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ts.tar.gz.asc
Source412:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_uk.tar.gz
Source413:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_uk.tar.gz.asc
Source414:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_uk.tar.gz
Source415:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_uk.tar.gz.asc
Source416:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ve.tar.gz
Source417:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_ve.tar.gz.asc
Source418:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_xh.tar.gz
Source419:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_xh.tar.gz.asc
Source420:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_zh-CN.tar.gz
Source421:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_zh-CN.tar.gz.asc
Source422:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_zh-CN.tar.gz
Source423:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_zh-CN.tar.gz.asc
Source424:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_zh-TW.tar.gz
Source425:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_helppack_zh-TW.tar.gz.asc
Source426:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_zh-TW.tar.gz
Source427:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_zh-TW.tar.gz.asc
Source428:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_zu.tar.gz
Source429:      %{source_url}/LibreOffice_%{verpkg}_Linux_x86-64_rpm_langpack_zu.tar.gz.asc
%global language_files1 %{S:200} %{S:202} %{S:204} %{S:206} %{S:208} %{S:210} %{S:212} %{S:214} %{S:216} %{S:218} %{S:220} %{S:222} %{S:224} %{S:226} %{S:228} %{S:230} %{S:232} %{S:234} %{S:236} %{S:238} %{S:240} %{S:242} %{S:244} %{S:246} %{S:248} %{S:250} %{S:252} %{S:254} %{S:256} %{S:258} %{S:260} %{S:262} %{S:264} %{S:266} %{S:268} %{S:270} %{S:272} %{S:274} %{S:276} %{S:278} %{S:280} %{S:282} %{S:284} %{S:286} %{S:288} %{S:290} %{S:292} %{S:294} %{S:296} %{S:298}
%global language_files2 %{S:300} %{S:302} %{S:304} %{S:306} %{S:308} %{S:310} %{S:312} %{S:314} %{S:316} %{S:318} %{S:320} %{S:322} %{S:324} %{S:326} %{S:328} %{S:330} %{S:332} %{S:334} %{S:336} %{S:338} %{S:340} %{S:342} %{S:344} %{S:346} %{S:348} %{S:350} %{S:352} %{S:354} %{S:356} %{S:358} %{S:360} %{S:362} %{S:364} %{S:366} %{S:368} %{S:370} %{S:372} %{S:374} %{S:376} %{S:378} %{S:380} %{S:382} %{S:384} %{S:386} %{S:388} %{S:390} %{S:392} %{S:394} %{S:396} %{S:398}
%global language_files3 %{S:400} %{S:402} %{S:404} %{S:406} %{S:408} %{S:410} %{S:412} %{S:414} %{S:416} %{S:418} %{S:420} %{S:422} %{S:424} %{S:426} %{S:428}
%endif

ExclusiveArch:  x86_64

BuildRequires: desktop-file-utils
BuildRequires: findutils
BuildRequires: gnupg2
BuildRequires: libappstream-glib
BuildRequires: tar
BuildRequires: util-linux
BuildRequires: zip

Requires: %{name}-writer%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-impress%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-draw%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-math%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-base%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-emailmerge%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%global instdir %{_libdir}
%global baseinstdir %{instdir}/libreoffice
%global sdkinstdir %{baseinstdir}/sdk
%global datadir %{_datadir}/%{name}
%global fontname opensymbol
# HACK: Get the data dir for -data subpackage. I haven't found any better
# way to do this...
%global oldname %{name}
%global name %{name}-data
%global lodatadocdir %{_pkgdocdir}
%global name %{oldname}

%if 0%{?__isa_bits} == 64
%global mark64 ()(64bit)
%endif

%global __provides_exclude_from ^%{baseinstdir}/.*

%global __requires_exclude ^lib.*lo\\.so.*$
%global __requires_exclude %__requires_exclude|^libaffine_uno_uno\\.so.*$
%global __requires_exclude %__requires_exclude|^libassuan\\.so.*$
%global __requires_exclude %__requires_exclude|^libavmediagst\\.so.*$
%global __requires_exclude %__requires_exclude|^libcached1\\.so.*$
%global __requires_exclude %__requires_exclude|^libCbc\\.so.*$
%global __requires_exclude %__requires_exclude|^libCbcSolver\\.so.*$
%global __requires_exclude %__requires_exclude|^libCgl\\.so.*$
%global __requires_exclude %__requires_exclude|^libClp\\.so.*$
%global __requires_exclude %__requires_exclude|^libclucene\\.so.*$
%global __requires_exclude %__requires_exclude|^libCoinMP\\.so.*$
%global __requires_exclude %__requires_exclude|^libCoinUtils.s8o
%global __requires_exclude %__requires_exclude|^libcollator_data\\.so.*$
%global __requires_exclude %__requires_exclude|^libcurl\\.so.*$
%global __requires_exclude %__requires_exclude|^libdbpool2\\.so.*$
%global __requires_exclude %__requires_exclude|^libdeploymentgui\\.so.*$
%global __requires_exclude %__requires_exclude|^libdict_ja\\.so.*$
%global __requires_exclude %__requires_exclude|^libdict_zh\\.so.*$
%global __requires_exclude %__requires_exclude|^libembobj\\.so.*$
%global __requires_exclude %__requires_exclude|^libemboleobj\\.so.*$
%global __requires_exclude %__requires_exclude|^libEngine12\\.so.*$
%global __requires_exclude %__requires_exclude|^libepoxy\\.so.*$
%global __requires_exclude %__requires_exclude|^libexslt\\.so.*$
%global __requires_exclude %__requires_exclude|^libfbclient\\.so.*$
%global __requires_exclude %__requires_exclude|^libgcc3_uno\\.so.*$
%global __requires_exclude %__requires_exclude|^libgpgmepp\\.so.*$
%global __requires_exclude %__requires_exclude|^libgpgme\\.so.*$
%global __requires_exclude %__requires_exclude|^libhsqldb\\.so.*$
%global __requires_exclude %__requires_exclude|^libi18nlangtag\\.so.*$
%global __requires_exclude %__requires_exclude|^libicudata\\.so.*$
%global __requires_exclude %__requires_exclude|^libicui18n\\.so.*$
%global __requires_exclude %__requires_exclude|^libicuuc\\.so.*$
%global __requires_exclude %__requires_exclude|^libindex_data\\.so.*$
%global __requires_exclude %__requires_exclude|^libjava_uno\\.so.*$
%global __requires_exclude %__requires_exclude|^libjpipe\\.so.*$
%global __requires_exclude %__requires_exclude|^libjuh\\.so.*$
%global __requires_exclude %__requires_exclude|^libjuhx\\.so.*$
%global __requires_exclude %__requires_exclude|^liblcms2\\.so.*$
%global __requires_exclude %__requires_exclude|^liblibreofficekitgtk\\.so.*$
%global __requires_exclude %__requires_exclude|^liblocaledata_.*\\.so.*$
%global __requires_exclude %__requires_exclude|^liblog_uno_uno\\.so.*$
%global __requires_exclude %__requires_exclude|^liblpsolve55\\.so.*$
%global __requires_exclude %__requires_exclude|^libofficebean\\.so.*$
%global __requires_exclude %__requires_exclude|^liborcus-.*\\.so.*$
%global __requires_exclude %__requires_exclude|^libOsiClp\\.so.*$
%global __requires_exclude %__requires_exclude|^libOsi\\.so.*$
%global __requires_exclude %__requires_exclude|^libpython*\\.so.*$
%global __requires_exclude %__requires_exclude|^libpyuno\\.so.*$
%global __requires_exclude %__requires_exclude|^libscriptframe\\.so.*$
%global __requires_exclude %__requires_exclude|^libsdbc2\\.so.*$
%global __requires_exclude %__requires_exclude|^libtextconv_dict\\.so.*$
%global __requires_exclude %__requires_exclude|^libucpchelp1\\.so.*$
%global __requires_exclude %__requires_exclude|^libucpdav1\\.so.*$
%global __requires_exclude %__requires_exclude|^libucpftp1\\.so.*$
%global __requires_exclude %__requires_exclude|^libucppkg1\\.so.*$
%global __requires_exclude %__requires_exclude|^libuno_cppuhelpergcc3\\.so.*$
%global __requires_exclude %__requires_exclude|^libuno_cppu\\.so.*$
%global __requires_exclude %__requires_exclude|^libunopkgapp\\.so.*$
%global __requires_exclude %__requires_exclude|^libuno_purpenvhelpergcc3\\.so.*$
%global __requires_exclude %__requires_exclude|^libuno_salhelpergcc3\\.so.*$
%global __requires_exclude %__requires_exclude|^libuno_sal\\.so.*$
%global __requires_exclude %__requires_exclude|^libunsafe_uno_uno\\.so.*$
%global __requires_exclude %__requires_exclude|^libxml2\\.so.*$
%global __requires_exclude %__requires_exclude|^libxmlsecurity\\.so.*$
%global __requires_exclude %__requires_exclude|^libxsec_xmlsec\\.so.*$
%global __requires_exclude %__requires_exclude|^libxslt\\.so.*$
%global __requires_exclude %__requires_exclude|^pyuno\\.so.*$


%description
LibreOffice is an Open Source, community-developed, office productivity suite.
It includes the key desktop applications, such as a word processor,
spreadsheet, presentation manager, formula editor and drawing program, with a
user interface and feature set similar to other office suites.  Sophisticated
and flexible, LibreOffice also works transparently with a variety of file
formats, including Microsoft Office File Formats.

%package filters
Summary: All import / export filters
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-graphicfilter%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-impress%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-writer%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-xsltfilter%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description filters
Metapackage to pull in all subpackages that contain import or export
filters.

%package core
Summary: Core modules for LibreOffice
Requires: %{name}-%{fontname}-fonts = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-plugin%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: liberation-sans-fonts, liberation-serif-fonts, liberation-mono-fonts
Requires: google-crosextra-caladea-fonts, google-crosextra-carlito-fonts
Requires: clm-david-fonts, clm-nachlieli-fonts
Requires: %{name}-langpack-en = %{?epoch:%{epoch}:}%{version}-%{release}
%ifarch %{java_arches}
# rhbz#949106 libreoffice-core drags in both openjdk 1.7.0 and 1.8.0
Requires: java-headless >= 1:1.6
%else
Obsoletes: libreoffice-nlpsolver < 1:7.4.0.0
Obsoletes: libreoffice-officebean < 1:7.4.0.0
Obsoletes: libreoffice-officebean-common < 1:7.4.0.0
Obsoletes: libreoffice-wiki-publisher < 1:7.4.0.0
%endif
Obsoletes: libreoffice-headless < 1:4.4.0.0
Obsoletes: libreoffice-math-debuginfo < 1:6.4.7.2
Provides: libreoffice-headless = %{?epoch:%{epoch}:}%{version}-%{release}
Provides: libreoffice-headless%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Obsoletes: libreoffice-bsh < 1:7.3.0.4
Obsoletes: libreoffice-rhino < 1:7.3.0.4
Obsoletes: libreoffice-gdb-debug-support < %{?epoch:%{epoch}:}%{version}-%{release}
Obsoletes: libreoffice-gtk4 < %{?epoch:%{epoch}:}%{version}-%{release}

%description core
The shared core libraries and support files for LibreOffice.

%package pyuno
Summary: Python support for LibreOffice
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description pyuno
Python bindings for the LibreOffice UNO component model. Allows scripts both
external to LibreOffice and within the internal LibreOffice scripting framework
to be written in python.

%package base
Summary: Database front-end for LibreOffice
Requires: firebird
Requires: postgresql-jdbc
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description base
GUI database front-end for LibreOffice. Allows creation and management of 
databases through a GUI.

%ifarch %{java_arches}

%package officebean
Summary: JavaBean for LibreOffice Components
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-officebean-common = %{?epoch:%{epoch}:}%{version}-%{release}

%description officebean
Allows embedding of LibreOffice documents within the Java environment. It
provides a Java AWT window into which the backend LibreOffice process draws
its visual representation

%package officebean-common
Summary: Common JavaBean for LibreOffice Components
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
BuildArch: noarch

%description officebean-common
Arch-independent part of %{name}-officebean.

%package wiki-publisher
Summary: Create Wiki articles on MediaWiki servers with LibreOffice
Requires: %{name}-writer%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description wiki-publisher
The Wiki Publisher enables you to create Wiki articles on MediaWiki servers
without having to know the syntax of the MediaWiki markup language. Publish
your new and existing documents transparently with writer to a wiki page.

%package nlpsolver
Summary: Non-linear solver engine for LibreOffice Calc
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description nlpsolver
A non-linear solver engine for Calc as an alternative to the default linear
programming model when more complex, nonlinear programming is required.

%endif

%package ogltrans
Summary: 3D OpenGL slide transitions for LibreOffice
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description ogltrans
OpenGL Transitions enable 3D slide transitions to be used in LibreOffice.
Requires good quality 3D support for your graphics card for best experience.

%package pdfimport
Summary: PDF Importer for LibreOffice Draw
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description pdfimport
The PDF Importer imports PDF into drawing documents to preserve layout
and enable basic editing of PDF documents.

%package %{fontname}-fonts
Summary: LibreOffice dingbats font
Requires: fontpackages-filesystem
BuildArch: noarch

%description %{fontname}-fonts
A dingbats font, OpenSymbol, suitable for use by LibreOffice for bullets and
mathematical symbols. 

%package writer
Summary: LibreOffice Word Processor Application
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pdfimport%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description writer
The LibreOffice Word Processor application.

%package emailmerge
Summary: Email mail-merge component for LibreOffice 
Requires: %{name}-writer%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description emailmerge
Enables the LibreOffice writer module to mail-merge to email.

%package calc
Summary: LibreOffice Spreadsheet Application
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pdfimport%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description calc
The LibreOffice Spreadsheet application.

%package draw
Summary: LibreOffice Drawing Application
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pdfimport%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-graphicfilter%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description draw
The LibreOffice Drawing Application.

%package impress
Summary: LibreOffice Presentation Application
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ogltrans%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pdfimport%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-graphicfilter%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description impress
The LibreOffice Presentation Application.

%package math
Summary: LibreOffice Equation Editor Application
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pdfimport%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description math 
The LibreOffice Equation Editor Application.

%package graphicfilter
Summary: LibreOffice Extra Graphic filters
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-data = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-filters = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description graphicfilter
The graphicfilter module for LibreOffice provides graphic filters, e.g. svg.

%package xsltfilter
Summary: Optional xsltfilter module for LibreOffice
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description xsltfilter
The xsltfilter module for LibreOffice, provides additional docbook and
xhtml export transforms. Install this to enable docbook export.

%package postgresql
Summary: PostgreSQL connector for LibreOffice
Requires: %{name}-base%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description postgresql
A PostgreSQL connector for the database front-end for LibreOffice. Allows
creation and management of PostgreSQL databases through a GUI.

%package ure
Summary: UNO Runtime Environment
Requires: %{name}-ure-common = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: unzip%{?_isa}
%ifarch %{java_arches}
#rhbz#1164551 we want to ensure that a libjvm.so of this arch is available
Requires: libjvm.so%{?mark64}
%endif

%description ure
UNO is the component model of LibreOffice. UNO offers interoperability between
programming languages, other components models and hardware architectures,
either in process or over process boundaries, in the Intranet as well as in the
Internet. UNO components may be implemented in and accessed from any
programming language for which a UNO implementation (AKA language binding) and
an appropriate bridge or adapter exists

%package ure-common
Summary: Common UNO Runtime Environment

%description ure-common
Arch-independent part of %{name}-ure.

%package sdk
Summary: Software Development Kit for LibreOffice
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: unzip%{?_isa}
%ifarch %{java_arches}
Requires: java-devel
%endif

%description sdk
The LibreOffice SDK is an add-on for the LibreOffice office suite. It provides
the necessary tools for programming using the LibreOffice APIs and for creating
extensions (UNO components) for LibreOffice.  To set the build environment for
building against the sdk use %{sdkinstdir}/setsdkenv_unix.sh.

%package sdk-doc
Summary: Software Development Kit documentation for LibreOffice

%description sdk-doc
This provides documentation for programming using the LibreOffice APIs
and examples of creating extensions (UNO components) for LibreOffice.

%package glade
Summary: Support for creating LibreOffice dialogs in glade
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description glade
%{name}-glade contains a catalog of LibreOffice-specific widgets for
glade tool to check the visual appearance of dialogs.

%package librelogo
Summary: LibreLogo scripting language
Requires: %{name}-writer%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}

%description librelogo
Enables LibreLogo scripting in Writer. LibreLogo is a Logo-like
programming language with interactive vectorgraphics for education and
DTP.

%package data
Summary: LibreOffice data files

%description data
%{name}-data contains platform-independent data files.

%package x11
Summary: LibreOffice generic X11 support plug-in
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Provides: %{name}-plugin = %{?epoch:%{epoch}:}%{version}-%{release}
Provides: %{name}-plugin%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Supplements: (%{name}-core%{?_isa} and Xserver)

%description x11
A plug-in for LibreOffice that enables generic X11 support.

%package gtk3
Summary: LibreOffice GTK+ 3 integration plug-in
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: gstreamer1(element-gtksink)%{?mark64}
Obsoletes: libreoffice-gtk2 < 1:6.2.0.0
Obsoletes: libreoffice-gtk2-debuginfo < 1:6.2.0.0
Supplements: (%{name}-core%{?_isa} and gtk3%{?_isa})

%description gtk3
A plug-in for LibreOffice that enables integration into GTK+ 3 environment.

%if 0
%package gtk4
Summary: LibreOffice GTK+ 4 experimental integration plug-in
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Supplements: (%{name}-core%{?_isa} and gtk4%{?_isa})

%description gtk4
An experimental plug-in for LibreOffice that enables integration into GTK+ 4 environment.
%endif

%package kf5
Summary: LibreOffice KDE Frameworks 5 integration plug-in
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Provides: %{name}-plugin = %{?epoch:%{epoch}:}%{version}-%{release}
Provides: %{name}-plugin%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}
Obsoletes: libreoffice-kde4 < 1:6.3.0.0
Obsoletes: libreoffice-kde5 < 1:6.4.7.3
Obsoletes: libreoffice-kde4-debuginfo < 1:6.3.0.0
Obsoletes: libreoffice-kde5-debuginfo < 1:6.4.7.3
Supplements: (%{name}-core%{?_isa} and plasma-workspace)

%description kf5
A plug-in for LibreOffice that enables integration into the KDE Frameworks 5.

%package -n libreofficekit
Summary: A library providing access to LibreOffice functionality
License: MPL-2.0
Obsoletes: libreoffice-libreofficekit-devel < %{?epoch:%{epoch}:}%{version}-%{release}

%description -n libreofficekit
LibreOfficeKit can be used to access LibreOffice functionality
through C/C++, without any need to use UNO.

For now it only offers document conversion (in addition to an
experimental tiled rendering API).

%define _langpack_common(DEg:j:l:) \
%{!-E: \
%{baseinstdir}/program/resource/%{-g:%{-g*}}%{!-g:%{-l*}}/LC_MESSAGES/*.mo  \
%{baseinstdir}/share/registry/res/registry_%{-l*}.xcd \
} \
%{-D: %{baseinstdir}/share/extensions/dict-%{-l*}} \
%{baseinstdir}/share/template/%{-l*} \
%{baseinstdir}/share/registry/Langpack-%{-l*}.xcd \
%{baseinstdir}/share/registry/res/fcfg_langpack_%{-l*}.xcd \
%{baseinstdir}/share/wizards/resources_%{-j:%{-j*}}%{!-j:%{-l*}}.properties \
%{nil}

# Defines a language pack subpackage.
#
# It's necessary to define language code (-l) and language name (-n).
# Additionally, it's possible
# * to require autocorr, or font for
#   given language,
# * to provide libreoffice-langpack-loc package, where loc is glibc
#   locale--this is necessary for yum to pick it automatically,
# * to require other, unrelated, packages,
# * to specify file serving as file list.
# For these, lower case character argument takes an argument specifying
# language, upper case character argument uses language from -l.
#
# All remaining arguments are considered to be files and added to the file
# list.
#
# Aa:  autocorr dependency
# c:   additional config file (just the name stem)
# D:   has dict
# E:   base (US English) langpack
# Ff:  font language dependency
# g:   glibc/java locale
# i:   additional language added to this package
# j:   java locale for the additional language
# k:   glibc locale for the additional language
# L:   internal (LibreOffice) language code, used in file names
# l:   language code, e.g., cs
# n:   language name, e.g., Czech
# p:   Provides: of libreoffice-langpack
# r:   comma-separated list of additional requires
# S:s: script classification (cjk, ctl). -S is only a marker, as it does
#      not add any .xcd into the package (the file does not exist for at
#      least one CTL-using locale, si)
# T    has help files
# Xx:  has autotext definitions
#
# Example:
# libreoffice-langpack-cs: langpack for Czech lang. requiring hyphen-cs,
# autocorr-cs, mythes-cs-CZ and suitable font:
# %%langpack -l cs -n Czech -A -m cs-CZ
#  b de           q  tu    z BCD  G IJK  N PQR  U    Z0123456789
%define langpack(Aa:c:EFf:g:i:j:k:L:l:n:p:r:S:s:TXx:D) \
%define lang %{-l:%{-l*}}%{!-l:%{error:Language code not defined}} \
%define _langpack_lang %{-L:%{-L*}}%{!-L:%{lang}} \
%define pkgname langpack-%{lang} \
%define langname %{-n:%{-n*}}%{!-n:%{error:Language name not defined}} \
\
%global langpack_langs %{langpack_langs} %{_langpack_lang} %{-i:%{-i*}} \
\
%package %{pkgname} \
Summary: %{langname} language pack for LibreOffice \
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release} \
%{-a:Requires: autocorr-%{-a*}}%{!-a:%{-A:Requires: autocorr-%{lang}}} \
%{-f:Recommends: langpacks-%{-f*}}%{!-f:%{-F:Recommends: langpacks-%{lang}}} \
%{-r:Requires: %{-r*}} \
%{-p:Provides: %{name}-langpack-%{-p*} = %{?epoch:%{epoch}:}%{version}-%{release}} \
%{-p:Provides: %{name}-langpack-%{-p*}%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}} \
%{-p:Supplements: (%{name}-core%{?_isa} and langpacks-%{-p*})} \
%{!-p:Supplements: (%{name}-core%{?_isa} and langpacks-%{lang})} \
%if 0%{?rhel} \
%{-T:Requires: %{name}-help-%{lang}} \
%else \
%{-T:Recommends: %{name}-help-%{lang}} \
%endif \
\
%description %{pkgname} \
Provides additional %{langname} translations and resources for LibreOffice. \
\
%{-T: \
%package help-%{lang} \
Summary: %{langname} help for LibreOffice \
Requires: %{name}-core%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release} \
\
%description help-%{lang} \
Provides %{langname} help for LibreOffice. \
\
%files help-%{lang} \
%docdir %{baseinstdir}/help/%{_langpack_lang} \
%{baseinstdir}/help/%{_langpack_lang} \
} \
\
%files %{pkgname} \
%{expand:%%_langpack_common %{-E} %{-D} -l %{_langpack_lang} %{-g:-g %{-g*} -j %{-g*}}} \
%{-x:%{baseinstdir}/share/autotext/%{-x*}}%{!-x:%{-X:%{baseinstdir}/share/autotext/%{_langpack_lang}}} \
%{-c:%{baseinstdir}/share/registry/%{-c*}.xcd} \
%{-s:%{baseinstdir}/share/registry/%{-s*}_%{_langpack_lang}.xcd} \
%{-i:%{expand:%%_langpack_common %{-E} %{-D} -l %{-i*} %{-k:-g %{-k*}} %{-j:-j %{-j*}}}} \
%{nil}

# Defines an auto-correction subpackage.
#
# i: add autocorrections from additional language
# l: language code
# n: language name
# L  the filename does not contain country code
#
# All remaining arguments are considered to be files and added to the file
# list.
%define autocorr(i:Ll:n:) \
%define lang %{-l:%{-l*}}%{!-l:%{error:Language code not defined}} \
%define pkgname autocorr-%{lang} \
%define langname %{-n:%{-n*}}%{!-n:%{error:Language name not defined}} \
\
%package -n %{pkgname} \
Summary: %{langname} auto-correction rules \
BuildArch: noarch \
\
%description -n %{pkgname} \
Rules for auto-correcting common %{langname} typing errors. \
\
%files -n %{pkgname} \
%doc LICENSE \
%dir %{_datadir}/autocorr \
%{-L:%{_datadir}/autocorr/acor_%{lang}.dat} \
%{!-L:%{_datadir}/autocorr/acor_%{lang}-*.dat} \
%{nil}

%langpack -l en -n English -F -A -E -L en-US -T -X -g en_US
%{baseinstdir}/share/extensions/dict-en

%if %{with langpacks}

%langpack -l af -n Afrikaans -F -A -X -D
%langpack -l ar -n Arabic -F -s ctl -T -X -D
%langpack -l as -n Assamese -F -X
%langpack -l bg -n Bulgarian -F -A -T -X -D
%langpack -l bn -n Bengali -F -T -X -D
%langpack -l br -n Breton -F -X -D
%langpack -l ca -n Catalan -F -A -T -X -D
%langpack -l cs -n Czech -F -A -T -X -D
%langpack -l cy -n Welsh -F -X
%langpack -l da -n Danish -F -A -T -X -D
%langpack -l de -n German -F -A -T -X -D
%langpack -l dz -n Dzongkha -F -s ctl -T -X
%langpack -l el -n Greek -F -A -T -X -D
%langpack -l eo -n Esperanto -F -T -X -D
%langpack -l es -n Spanish -F -A -T -X -D
%langpack -l et -n Estonian -F -T -X -D
%langpack -l eu -n Basque -F -T -X
%langpack -l fa -n Farsi -A -s ctl -X -D
%langpack -l fi -n Finnish -F -r libreoffice-voikko -A -T -X
%langpack -l fr -n French -F -A -T -X -D
%langpack -l fy -n Frisian -F -X
%langpack -l ga -n Irish -F -A -X
%langpack -l gl -n Galician -F -T -X -D
%langpack -l gu -n Gujarati -F -s ctl -T -X -D
%langpack -l he -n Hebrew -F -s ctl -T -X -D
%langpack -l hi -n Hindi -F -s ctl -T -X -D
%langpack -l hr -n Croatian -F -A -T -X -D
%langpack -l hu -n Hungarian -F -A -T -X -D
%{baseinstdir}/share/wordbook/hu_AkH11.dic
%langpack -l id -n Indonesian -F -T -X -D
%langpack -l it -n Italian -F -A -T -X -D
%langpack -l ja -n Japanese -F -A -s cjk -T -X
%langpack -l kk -n Kazakh -F -X
%langpack -l kn -n Kannada -F -X
%langpack -l ko -n Korean -F -A -s cjk -T -X -D
%langpack -l lt -n Lithuanian -F -A -T -X -D
%langpack -l lv -n Latvian -F -T -X -D
%langpack -l mai -n Maithili -F -X
%langpack -l ml -n Malayalam -F -X
%langpack -l mr -n Marathi -F -X
%langpack -l nb -n Bokmal -F -T -X
%langpack -l nl -n Dutch -F -A -T -X -X -D
%langpack -l nn -n Nynorsk -F -T -D
%define langpack_lang Southern Ndebele
%langpack -l nr -n %{langpack_lang} -F -X
%define langpack_lang Northern Sotho
%langpack -l nso -n %{langpack_lang} -F -X
%langpack -l or -n Odia -F -s ctl -X
%langpack -l pa -n Punjabi -F -s ctl -L pa-IN -g pa_IN -X
%langpack -l pl -n Polish -F -A -T -X -D
%define langpack_lang Brazilian Portuguese
%langpack -l pt-BR -n %{langpack_lang} -f pt_BR -a pt -p pt_BR -T -X -g pt_BR -D
%langpack -l pt-PT -n Portuguese -f pt -a pt -p pt_PT -T -L pt -x pt
%{baseinstdir}/share/extensions/dict-pt-PT
%langpack -l ro -n Romanian -A -F -T -X -D
%langpack -l ru -n Russian -F -A -T -X -D
%langpack -l si -n Sinhalese -F -S ctl -T -X -D
%langpack -l sk -n Slovak -F -A -T -X -D
%langpack -l sl -n Slovenian -F -A -T -X -D
%{baseinstdir}/share/wordbook/sl.dic

#rhbz#452379 clump serbian translations together
%langpack -l sr -n Serbian -F -A -i sr-Latn -k sr@latin -j sr_Latn -x sr*
%{baseinstdir}/share/extensions/dict-sr
%langpack -l ss -n Swati -F -X
%define langpack_lang Southern Sotho
# note that langpacks-st seems to be missing as of the time of writing, so no -F here
%langpack -l st -n %{langpack_lang} -X
%langpack -l sv -n Swedish -F -A -T -X -D
%langpack -l ta -n Tamil -F -s ctl -T -X
%langpack -l te -n Telugu -F -X -D
%langpack -l th -n Thai -F -s ctl -c ctlseqcheck_th -X -D
%langpack -l tn -n Tswana -F -X
%langpack -l tr -n Turkish -F -A -T -X -D
%langpack -l ts -n Tsonga -F -X
%langpack -l uk -n Ukrainian -F -T -X -D
%langpack -l ve -n Venda -F -X
%langpack -l xh -n Xhosa -F -X

%define langpack_lang Simplified Chinese
%langpack -l zh-Hans -n %{langpack_lang} -f zh_CN -a zh -p zh_CN -s cjk -T -L zh-CN -x zh-CN -g zh_CN
%{baseinstdir}/share/template/common/l10n/zh_CN_ott_normal.ott

%define langpack_lang Traditional Chinese
%langpack -l zh-Hant -n %{langpack_lang} -f zh_TW -a zh -p zh_TW -s cjk -T -L zh-TW -x zh-TW -g zh_TW

%langpack -l zu -n Zulu -F -X -D
%undefine langpack_lang

%endif

%autocorr -l en -n English

%if %{with langpacks}

%autocorr -l af -n Afrikaans
%autocorr -l bg -n Bulgarian
%autocorr -l ca -n Catalan
%autocorr -l cs -n Czech
%autocorr -l da -n Danish
%autocorr -l de -n German -L
%define autocorr_lang Lower Sorbian
%autocorr -l dsb -n %{autocorr_lang} -L
%autocorr -l el -n Greek
%autocorr -l es -n Spanish -L
%autocorr -l fa -n Farsi
%autocorr -l fi -n Finnish
%autocorr -l fr -n French -L
%autocorr -l ga -n Irish
%autocorr -l hr -n Croatian
%define autocorr_lang Upper Sorbian
%autocorr -l hsb -n %{autocorr_lang} -L
%autocorr -l hu -n Hungarian
%autocorr -l is -n Icelandic
%autocorr -l it -n Italian -L
%autocorr -l ja -n Japanese
%autocorr -l ko -n Korean
%autocorr -l lb -n Luxembourgish
%autocorr -l lt -n Lithuanian
%autocorr -l mn -n Mongolian
%autocorr -l nl -n Dutch
%autocorr -l pl -n Polish
%autocorr -l pt -n Portuguese
%autocorr -l ro -n Romanian
%autocorr -l ru -n Russian
%autocorr -l sk -n Slovak
%autocorr -l sl -n Slovenian
%autocorr -l sr -n Serbian
%autocorr -l sv -n Swedish
%autocorr -l tr -n Turkish
%autocorr -l vi -n Vietnamese
%autocorr -l vro -n Võro
%autocorr -l zh -n Chinese

%endif

%define make_autocorr_aliases(l:) \
%{?-l: \
for lang in %{*}; do \
    ln -sf acor_%{-l*}.dat acor_$lang.dat \
done \
} \
%{!?-l:%{error:-l must be present}}

%prep
# verify tarballs
%if %{with verify}
gpg2 --dearmor < %{SOURCE6} > keyring.gpg
for i in %{SOURCE0} %{SOURCE2} %{SOURCE4};do
  gpgv2 --keyring ./keyring.gpg $i.asc $i
done
%if %{with langpacks}
for i in %{language_files1} %{language_files2} %{language_files3} ;do
  gpgv2 --keyring ./keyring.gpg $i.asc $i
done
%endif
%endif

%autosetup -n LibreOffice_%{ver}_Linux_x86-64_rpm

for i in %{S:2} %{S:4};do
  tar xf $i --strip-components 1
done

%if %{with langpacks}
mkdir -p langpacks-RPMS
pushd langpacks-RPMS
for i in %{language_files1} %{language_files2} %{language_files3} ;do
  tar xf $i --strip-components 2
done
popd
%endif

mkdir -p %{_vpath_builddir}

pushd RPMS
  rm -rf desktop-integration
  rm -rf userland
  rm -f *onlineupdate*.rpm
  rm -f jre-*.rpm jdk-*.rpm
  rm -f *extension-{beanshell,javascript}*.rpm
  for rpm in *.rpm ; do
    rpm2cpio ${rpm} | ( cd ../%{_vpath_builddir} && cpio -imd --no-absolute-filenames )
  done
popd

rm -rf %{_vpath_builddir}/opt/libreoffice%{verprod}/share/extensions/dict-{es,fr}/

mv %{_vpath_builddir}/opt/libreoffice%{verprod}/share/wizards/resources_en_US.properties \
  wizards_resources_en_US.properties

%if %{with langpacks}
pushd langpacks-RPMS
  for rpm in *.rpm ; do
    rpm2cpio ${rpm} | ( cd ../%{_vpath_builddir} && cpio -imd --no-absolute-filenames )
  done
popd
mv %{_vpath_builddir}/opt/libreoffice%{verprod}/share/extensions/dict-{no,nn}

for lang in \
  am ast be bn_IN bo brx bs ca_valencia ckb dgo dsb en_GB en_ZA fur gd gug hsb \
  is ka kab km kmr_Latn kok ks lb lo mk mn mni my ne oc om rw sa_IN sat sd sid \
  sq sw_TZ szl tg tt ug uz vec vi
do
  rm -f %{_vpath_builddir}/opt/libreoffice%{verprod}/share/wizards/resources_$lang.properties 
done

%else
rm -f %{_vpath_builddir}/opt/libreoffice%{verprod}/share/wizards/resources_*.properties
%endif

mv wizards_resources_en_US.properties %{_vpath_builddir}/opt/libreoffice%{verprod}/share/wizards/resources_en_US.properties

rm -rf %{_vpath_builddir}/usr/bin
rm -rf %{_vpath_builddir}/usr/share/applications

pushd %{_vpath_builddir}/opt/libreoffice%{verprod}
rm -rf share/Scripts/{beanshell,javascript}

chmod -x program/python.bin-gdb.py

popd

#set standard permissions for rpmlint
find %{_vpath_builddir} -exec chmod +w {} \;
find %{_vpath_builddir} -type d -exec chmod 0755 {} \;

rm -rf readmes
mv -f %{_vpath_builddir}/opt/libreoffice%{verprod}/readmes .
mv -f %{_vpath_builddir}/opt/libreoffice%{verprod}/{CREDITS,LICENSE,NOTICE}* .

pushd %{_vpath_builddir}

rename %{verprod} '' usr/share/metainfo/*.xml
rename %{verprod} '' usr/share/mime/packages/*.xml
rename %{verprod} '' usr/share/icons/hicolor/*/*/*.{png,svg}

# Fix desktop files
sed \
  -e "/^Name.*=/s|\ %{verprod}||g" \
  -e "/^Icon=/s|%{verprod}||g" \
  -e "/^Exec=/s|%{verprod}||g" \
  -i opt/libreoffice%{verprod}/share/xdg/*.desktop || exit 1

cp %{S:7} opt/libreoffice%{verprod}/share/xdg/extension-manager.desktop

popd

cp %{S:9} .
cp %{S:10} .


%build


%install
install -m 0755 -d %{buildroot}%{instdir}
install -m 0755 -d %{buildroot}%{baseinstdir}

mv %{_vpath_builddir}/opt/libreoffice%{verprod}/* %{buildroot}%{baseinstdir}
chmod -R +w %{buildroot}%{baseinstdir}

# postprocessing and tweaks

#configure sdk
pushd %{buildroot}%{sdkinstdir}
  mv setsdkenv_unix{,.sh}
  grep '@[A_Z0-9_]\+@' setsdkenv_unix.sh && exit 1
  chmod 755 setsdkenv_unix.sh
  # we don't want to install the input file
  rm -f setsdkenv_unix.sh.in
# TODO: is this still necessary?
#fix permissions
    find examples -type f -exec chmod -x {} \;
popd

#ensure a template dir for each lang
pushd %{buildroot}%{baseinstdir}/share/template
for I in %{langpack_langs}; do
    mkdir -p $I
done
popd

#Set some aliases to canonical autocorrect language files for locales with matching languages
pushd %{buildroot}%{baseinstdir}/share/autocorr

%make_autocorr_aliases -l en-GB en-AG en-AU en-BS en-BW en-BZ en-CA en-DK en-GH en-HK en-IE en-IN en-JM en-NG en-NZ en-SG en-TT
%make_autocorr_aliases -l en-US en-PH
#en-ZA exists and has a good autocorrect file with two or three extras that make sense for 
#neighbouring english speaking territories
%make_autocorr_aliases -l en-ZA en-NA en-ZW
%if %{with langpacks}
%make_autocorr_aliases -l af-ZA af-NA
%make_autocorr_aliases -l nl-NL nl-AW
%make_autocorr_aliases -l sv-SE sv-FI
%else
rm -f acor_[a-df-z]*.dat acor_e[lsu]*.dat
%endif
popd
#rhbz#484055 make these shared across multiple applications
install -m 0755 -d %{buildroot}%{_datadir}
mv -f %{buildroot}%{baseinstdir}/share/autocorr %{buildroot}%{_datadir}/autocorr
ln -sr %{buildroot}%{_datadir}/autocorr %{buildroot}%{baseinstdir}/share/autocorr

#remove it in case we didn't build with gcj
rm -f %{buildroot}%{baseinstdir}/program/classes/sandbox.jar
# we don't need this in the install
rm -f %{buildroot}%{baseinstdir}/program/classes/smoketest.jar

#remove dummy .dat files
rm -f %{buildroot}%{baseinstdir}/program/root?.dat

rm -rf %{buildroot}%{baseinstdir}/program/__pycache__

# rhbz#477435 package opensymbol separately
pushd %{buildroot}%{baseinstdir}/program/resource/common/fonts
install -d -m 0755 %{buildroot}%{_fontdir}
install -p -m 0644 *.ttf %{buildroot}%{_fontdir}
popd
rm -rf %{buildroot}%{baseinstdir}/program/resource/common/fonts/*.?tf
rm -rf %{buildroot}%{baseinstdir}/share/fonts/truetype/*.?tf

# move platform-independent data into shared dir
install -m 0755 -d %{buildroot}%{datadir}
# rhbz#1473749 ensure display of files in license/about dialogs works
ln -sr %{buildroot}%{lodatadocdir}/CREDITS.fodt %{buildroot}%{baseinstdir}/CREDITS.fodt
ln -sr %{buildroot}%{lodatadocdir}/LICENSE.html %{buildroot}%{baseinstdir}/LICENSE.html

#ensure that no sneaky un-prelinkable, un-fpic or non executable shared libs 
#have snuck through
pic=0
executable=0
for foo in `find %{buildroot}%{instdir} -name "*" -exec file {} \;| grep ": ELF" | cut -d: -f 1` ; do
    chmod +wx $foo
    ls -asl $foo
    result=`readelf -d $foo | grep TEXTREL` || true
    if [ "$result" != "" ]; then
        echo "TEXTREL Warning: $foo is b0rked (-fpic missing)"
        pic=1
    fi
    result=`readelf -l $foo | grep GNU_STACK | grep RWE` || true
    if [ "$result" != "" ]; then
        echo "GNU_STACK Warning: $foo is b0rked (-noexecstack missing)"
        executable=1
    fi
done
if [ $pic == 1 ]; then false; fi
if [ $executable == 1 ]; then false; fi

#make up some /usr/bin scripts
install -m 0755 -d %{buildroot}%{_bindir}

pushd %{buildroot}%{_bindir}
echo \#\!/usr/bin/sh > ooffice
echo exec libreoffice \"\$@\" >> ooffice
chmod a+x ooffice

echo \#\!/usr/bin/sh > ooviewdoc
echo exec libreoffice --view \"\$@\" >> ooviewdoc
chmod a+x ooviewdoc

for app in base calc draw impress math writer; do
    echo \#\!/usr/bin/sh > oo$app
    echo exec libreoffice --$app \"\$@\" >> oo$app
    chmod a+x oo$app
done

sed -e s/LAUNCHER/unopkg/g -e s/BRAND/libreoffice/g %{S:8} > unopkg
chmod a+x unopkg

sed -e s/LAUNCHER/soffice/g -e s/BRAND/libreoffice/g %{S:8} > libreoffice
chmod a+x libreoffice

# rhbz#499474 provide a /usr/bin/soffice for .recently-used.xbel
ln -sr %{buildroot}%{baseinstdir}/program/soffice %{buildroot}%{_bindir}/soffice
# rhbz#499474 provide a /usr/bin/openoffice.org for backwards compat
ln -s libreoffice openoffice.org
popd

pushd %{buildroot}%{baseinstdir}/share/xdg/
# rhbz#186515 do not show startcenter
desktop-file-edit --set-key=NoDisplay --set-value=true startcenter.desktop

desktop-file-edit \
  --remove-category=Graphics \
  --remove-category=2DGraphics \
  --remove-category=VectorGraphics \
  draw.desktop
  
desktop-file-edit \
  --remove-category=Education \
  --remove-category=Science \
  --remove-category=Math \
  math.desktop

# relocate the .desktop and icon files
install -m 0755 -d %{buildroot}%{_datadir}/applications

for app in base calc draw extension-manager impress math startcenter writer xsltfilter; do
  desktop-file-install \
    --vendor="%{name}" --mode 0644 \
    --dir %{buildroot}/usr/share/applications \
    $app.desktop
done

popd

mv %{_vpath_builddir}/usr/share/icons %{buildroot}%{_datadir}/

mv %{_vpath_builddir}/usr/share/mime %{buildroot}%{_datadir}/

mv %{_vpath_builddir}/usr/share/metainfo %{buildroot}%{_datadir}/

# restrict abipkgdiff to shared objects that actually have a stable ABI
for pkg in core base officebean ogltrans pdfimport calc writer impress graphicfilter postgresql ure pyuno x11 gtk3 kf5 libreofficekit; do
    cat > %{buildroot}%{baseinstdir}/program/${pkg}.abignore << _EOF
[suppress_file]
file_name_not_regexp=.*\.so\.[0-9]+
_EOF
done

rm -rf %{buildroot}%{baseinstdir}/readmes
rm -rf %{buildroot}%{baseinstdir}/licenses
rm -rf %{buildroot}%{baseinstdir}/share/theme_definitions

# rhbz#452385 to auto have postgres in classpath if subsequently installed
sed -i -e "s#URE_MORE_JAVA_CLASSPATH_URLS.*#& file:///usr/share/java/postgresql-jdbc.jar#" \
  %{buildroot}%{baseinstdir}/program/fundamentalrc

# move glade catalog to system glade dir
install -m 0755 -d %{buildroot}%{_datadir}/glade/catalogs
mv %{buildroot}%{baseinstdir}/share/glade/libreoffice-catalog.xml %{buildroot}%{_datadir}/glade/catalogs
install -m 0755 -d %{buildroot}%{_datadir}/glade3/catalogs
ln -sr %{buildroot}%{_datadir}/glade/catalogs/libreoffice-catalog.xml %{buildroot}%{_datadir}/glade3/catalogs

# rhbz#1215800 install symbolic icons
install -m 0755 -d %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
for symb in \
  %{SOURCE42} %{SOURCE43} %{SOURCE44} %{SOURCE45} %{SOURCE46} %{SOURCE47} %{SOURCE48}
do
  install -m 0644 -p $symb %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
done

# install man pages
install -m 0755 -d %{buildroot}%{_mandir}/man1
install -m 0644 -p %{name}.1 %{buildroot}%{_mandir}/man1
install -m 0644 -p unopkg.1 %{buildroot}%{_mandir}/man1
for app in oobase oocalc oodraw ooffice ooimpress oomath ooviewdoc oowriter openoffice.org soffice; do
  echo '.so man1/libreoffice.1' > $app.1
  install -m 0644 -p $app.1 %{buildroot}%{_mandir}/man1
done

%ifarch %{java_arches}
# rhbz#1247399 - move stable API jars to noarch java location
install -m 0755 -d %{buildroot}%{_javadir}/%{name}
for jar in %{buildroot}%{baseinstdir}/program/classes/*.jar; do
  j=`basename $jar`
  case ${j%.jar} in
    juh|jurt|libreoffice|ridl|unoloader|unoil|officebean)
        mv $jar %{buildroot}%{_javadir}/%{name}
        ln -sr %{buildroot}%{_javadir}/%{name}/$j $jar
        ;;
  esac
done
%else
# make sure something creates this dir
install -m 0755 -d %{buildroot}%{baseinstdir}/share/extensions
# and remove this
rm -f %{buildroot}%{baseinstdir}/program/officebean.abignore
%endif

%check
desktop-file-validate %{buildroot}%{_datadir}/applications/*.desktop
appstream-util validate-relax --nonet %{buildroot}%{_metainfodir}/*.appdata.xml

%files

%files filters

%files core
%dir %{baseinstdir}
%{baseinstdir}/CREDITS.fodt
%{baseinstdir}/LICENSE.html
%dir %{baseinstdir}/help
%{baseinstdir}/help/idxcaption.xsl
%{baseinstdir}/help/idxcontent.xsl
%{baseinstdir}/help/main_transform.xsl
%{baseinstdir}/help/*.{html,css,js}
%{baseinstdir}/help/media
%{baseinstdir}/presets
%dir %{baseinstdir}/program
%{baseinstdir}/program/core.abignore
%{baseinstdir}/program/libcairocanvaslo.so
%ifarch %{java_arches}
%dir %{baseinstdir}/program/classes
%{baseinstdir}/program/classes/commonwizards.jar
%{baseinstdir}/program/classes/form.jar
%{baseinstdir}/program/classes/query.jar
%{baseinstdir}/program/classes/report.jar
%{baseinstdir}/program/classes/ScriptFramework.jar
%{baseinstdir}/program/classes/ScriptProviderForJava.jar
%{baseinstdir}/program/classes/table.jar
%{baseinstdir}/program/classes/unoil.jar
%{baseinstdir}/program/classes/XMergeBridge.jar
%{baseinstdir}/program/classes/xmerge.jar
%endif
%{baseinstdir}/program/libcmdmaillo.so
%{baseinstdir}/program/libdeploymentgui.so
%{baseinstdir}/program/libdlgprovlo.so
%{baseinstdir}/program/libexpwraplo.so
%{baseinstdir}/program/gdbtrace
%{baseinstdir}/program/gengal
%{baseinstdir}/program/gengal.bin
%{baseinstdir}/program/libldapbe2lo.so
%{baseinstdir}/program/libacclo.so
%{baseinstdir}/program/libanimcorelo.so
%{baseinstdir}/program/libavmedia*.so
%{baseinstdir}/program/libbiblo.so
%{baseinstdir}/program/libcached1.so
%{baseinstdir}/program/libchart*lo.so
%{baseinstdir}/program/libclewlo.so
%{baseinstdir}/program/libcollator_data.so
%{baseinstdir}/program/libcuilo.so
%{baseinstdir}/program/libdbalo.so
%{baseinstdir}/program/libdbahsqllo.so
%{baseinstdir}/program/libdbaselo.so
%{baseinstdir}/program/libdbaxmllo.so
#{baseinstdir}/program/libdbmmlo.so
%{baseinstdir}/program/libdbpool2.so
%{baseinstdir}/program/libdbulo.so
%{baseinstdir}/program/libdesktop_detectorlo.so
%{baseinstdir}/program/libdict_ja.so
%{baseinstdir}/program/libdict_zh.so
%{baseinstdir}/program/libembobj.so
%{baseinstdir}/program/libemboleobj.so
%{baseinstdir}/program/libevoab*.so
%{baseinstdir}/program/libicglo.so
%{baseinstdir}/program/libindex_data.so
%{baseinstdir}/program/libfilelo.so
%{baseinstdir}/program/libflatlo.so
%ifarch %{java_arches}
%{baseinstdir}/program/libjdbclo.so
%endif
%{baseinstdir}/program/libLanguageToollo.so
%{baseinstdir}/program/libloglo.so
%{baseinstdir}/program/liblocaledata_en.so
%{baseinstdir}/program/liblocaledata_es.so
%{baseinstdir}/program/liblocaledata_euro.so
%{baseinstdir}/program/liblocaledata_others.so
%{baseinstdir}/program/libmozbootstraplo.so
%{baseinstdir}/program/libmysql_jdbclo.so
%{baseinstdir}/program/libmysqlclo.so
%{baseinstdir}/program/libodbclo.so
%{baseinstdir}/program/libooxlo.so
%{baseinstdir}/program/libpcrlo.so
%{baseinstdir}/program/libpdffilterlo.so
%{baseinstdir}/program/libprotocolhandlerlo.so
%{baseinstdir}/program/libscnlo.so
%{baseinstdir}/program/libscriptframe.so
%{baseinstdir}/program/libsdlo.so
%{baseinstdir}/program/libsdbc2.so
%{baseinstdir}/program/libsdbtlo.so
%{baseinstdir}/program/libsddlo.so
%{baseinstdir}/program/libsduilo.so
%{baseinstdir}/program/libstoragefdlo.so
%{baseinstdir}/program/libswdlo.so
%{baseinstdir}/program/libswlo.so
%{baseinstdir}/program/libtextconv_dict.so
%{baseinstdir}/program/libtextconversiondlgslo.so
%{baseinstdir}/program/libucpchelp1.so
%{baseinstdir}/program/libucpdav1.so
%{baseinstdir}/program/libucpftp1.so
%{baseinstdir}/program/libucppkg1.so
%{baseinstdir}/program/libunopkgapp.so
%{baseinstdir}/program/libxsec_xmlsec.so
# TODO how useful this is in Fedora?
%{baseinstdir}/program/liblosessioninstalllo.so
%{baseinstdir}/program/libmigrationoo2lo.so
%{baseinstdir}/program/libmigrationoo3lo.so
%{baseinstdir}/program/libmsformslo.so

%{baseinstdir}/program/libCbc.so.*
%{baseinstdir}/program/libCbcSolver.so.*
%{baseinstdir}/program/libCgl.so.*
%{baseinstdir}/program/libClp.so.*
%{baseinstdir}/program/libCoinMP.so.*
%{baseinstdir}/program/libCoinUtils.so.*
%{baseinstdir}/program/libEngine12.so
%{baseinstdir}/program/libOsi.so.*
%{baseinstdir}/program/libOsiClp.so.*
%{baseinstdir}/program/libassuan.so.*
%{baseinstdir}/program/libclucene.so
%{baseinstdir}/program/libcurl.so.*
%{baseinstdir}/program/libepoxy.so
%{baseinstdir}/program/libetonyek-0.1-lo.so.*
%{baseinstdir}/program/libexslt.so.0
%{baseinstdir}/program/libfbclient.so.*
%{baseinstdir}/program/libgpg-error-lo.so.*
%{baseinstdir}/program/libgpgme.so.*
%{baseinstdir}/program/libgpgmepp.so.*
%{baseinstdir}/program/libicudata.so.*
%{baseinstdir}/program/libicui18n.so.*
%{baseinstdir}/program/libicuuc.so.*
%{baseinstdir}/program/liblangtag-lo.so.*
%{baseinstdir}/program/liblcms2.so.*
%{baseinstdir}/program/liblpsolve55.so
%{baseinstdir}/program/libmergedlo.so
%{baseinstdir}/program/libmwaw-0.3-lo.so.*
%{baseinstdir}/program/libodfgen-0.1-lo.so.*
%{baseinstdir}/program/liborcus-0.17.so.*
%{baseinstdir}/program/liborcus-parser-0.17.so.*
%{baseinstdir}/program/libpdfiumlo.so
%{baseinstdir}/program/libpython3.8.so
%{baseinstdir}/program/libpython3.8.so.*
%{baseinstdir}/program/libraptor2-lo.so.*
%{baseinstdir}/program/librasqal-lo.so.*
%{baseinstdir}/program/librdf-lo.so.*
%{baseinstdir}/program/librevenge-0.0-lo.so.*
%{baseinstdir}/program/libstaroffice-0.0-lo.so.*
%{baseinstdir}/program/libwpd-0.10-lo.so.*
%{baseinstdir}/program/libwpg-0.3-lo.so.*
%{baseinstdir}/program/libwps-0.4-lo.so.*
%{baseinstdir}/program/libxml2.so.*
%{baseinstdir}/program/libxslt.so.*
%{baseinstdir}/program/minidump_upload

%{baseinstdir}/program/opencl
%dir %{baseinstdir}/program/opengl
%{baseinstdir}/program/opengl/*.glsl
%{baseinstdir}/program/types/offapi.rdb
%{baseinstdir}/program/pagein-common
%attr(0755,root,root) %{baseinstdir}/program/python.bin-gdb.py
%dir %{baseinstdir}/program/resource
%dir %{baseinstdir}/program/resource/common
%dir %{baseinstdir}/program/resource/common/fonts
%{baseinstdir}/program/senddoc
%dir %{baseinstdir}/program/services
%{baseinstdir}/program/services/services.rdb
%{baseinstdir}/program/libslideshowlo.so
%{baseinstdir}/program/libsmlo.so
%{baseinstdir}/program/libsmdlo.so
%{baseinstdir}/program/libucpcmis1lo.so
%{baseinstdir}/program/lounorc
%{baseinstdir}/program/uri-encode
%{baseinstdir}/program/versionrc
%dir %{baseinstdir}/share
%dir %{baseinstdir}/share/classification
%{baseinstdir}/share/classification/example*.xml
%dir %{baseinstdir}/share/fonts
%dir %{baseinstdir}/share/fonts/truetype
%{baseinstdir}/share/fonts/truetype/fc_local.conf
%dir %{baseinstdir}/share/Scripts
%ifarch %{java_arches}
%{baseinstdir}/share/Scripts/java
%endif
%dir %{baseinstdir}/share/autotext
%dir %{_datadir}/autocorr
%{baseinstdir}/share/autocorr
%{baseinstdir}/share/basic
%dir %{baseinstdir}/share/config
%{baseinstdir}/share/config/images_breeze.zip
%{baseinstdir}/share/config/images_breeze_svg.zip
%{baseinstdir}/share/config/images_breeze_dark.zip
%{baseinstdir}/share/config/images_breeze_dark_svg.zip
%{baseinstdir}/share/config/images_colibre.zip
%{baseinstdir}/share/config/images_colibre_svg.zip
%{baseinstdir}/share/config/images_colibre_dark.zip
%{baseinstdir}/share/config/images_colibre_dark_svg.zip
%{baseinstdir}/share/config/images_elementary.zip
%{baseinstdir}/share/config/images_elementary_svg.zip
%{baseinstdir}/share/config/images_helpimg.zip
%{baseinstdir}/share/config/images_karasa_jaga.zip
%{baseinstdir}/share/config/images_karasa_jaga_svg.zip
%{baseinstdir}/share/config/images_sifr.zip
%{baseinstdir}/share/config/images_sifr_dark.zip
%{baseinstdir}/share/config/images_sifr_dark_svg.zip
%{baseinstdir}/share/config/images_sifr_svg.zip
%{baseinstdir}/share/config/images_sukapura.zip
%{baseinstdir}/share/config/images_sukapura_svg.zip
%{baseinstdir}/share/config/images_sukapura_dark.zip
%{baseinstdir}/share/config/images_sukapura_dark_svg.zip
%dir %{baseinstdir}/share/fingerprint
%{baseinstdir}/share/fingerprint/*.conf
%{baseinstdir}/share/fingerprint/*.lm
%dir %{baseinstdir}/share/firebird
%{baseinstdir}/share/firebird/*
%dir %{baseinstdir}/share/liblangtag
%{baseinstdir}/share/liblangtag/*.xml
%{baseinstdir}/share/liblangtag/common/*/*.xml
%dir %{baseinstdir}/share/tipoftheday
%{baseinstdir}/share/tipoftheday/*
%dir %{baseinstdir}/share/toolbarmode
%{baseinstdir}/share/toolbarmode/*
%dir %{baseinstdir}/share/config/soffice.cfg
%{baseinstdir}/share/config/soffice.cfg/modules
%{baseinstdir}/share/config/soffice.cfg/*/ui
%{baseinstdir}/share/palette
%{baseinstdir}/share/config/webcast
%{baseinstdir}/share/config/wizard
%dir %{baseinstdir}/share/dtd
%{baseinstdir}/share/dtd/officedocument
%{baseinstdir}/share/gallery
%dir %{baseinstdir}/share/labels
%{baseinstdir}/share/labels/labels.xml
%dir %{baseinstdir}/share/numbertext
%{baseinstdir}/share/numbertext/*.sor
%dir %{baseinstdir}/share/psprint
%config %{baseinstdir}/share/psprint/psprint.conf
%{baseinstdir}/share/psprint/driver
%dir %{baseinstdir}/share/registry
%{baseinstdir}/share/registry/draw.xcd
%{baseinstdir}/share/registry/gnome.xcd
%{baseinstdir}/share/registry/lingucomponent.xcd
%{baseinstdir}/share/registry/main.xcd
%{baseinstdir}/share/registry/math.xcd
%{baseinstdir}/share/registry/oo-ad-ldap.xcd.sample
%{baseinstdir}/share/registry/oo-ldap.xcd.sample
%dir %{baseinstdir}/share/registry/res
%dir %{baseinstdir}/share/template
%dir %{baseinstdir}/share/template/common
%{baseinstdir}/share/template/common/draw
%{baseinstdir}/share/template/common/internal
%{baseinstdir}/share/template/common/officorr
%{baseinstdir}/share/template/common/offimisc
%{baseinstdir}/share/template/common/personal
%{baseinstdir}/share/template/common/presnt
%{baseinstdir}/share/template/common/styles
%{baseinstdir}/share/template/common/wizard
%dir %{baseinstdir}/share/template/common/l10n
%{baseinstdir}/share/template/wizard
%dir %{baseinstdir}/share/wordbook
%{baseinstdir}/share/wordbook/en-GB.dic
%{baseinstdir}/share/wordbook/en-US.dic
%{baseinstdir}/share/wordbook/technical.dic
%{_bindir}/unopkg
%{_datadir}/applications/libreoffice-extension-manager.desktop
%{_mandir}/man1/unopkg.1*
%{baseinstdir}/program/libxmlsecurity.so
%{baseinstdir}/program/libwriterperfectlo.so
%{baseinstdir}/program/libucpgio1lo.so
%{baseinstdir}/program/types/oovbaapi.rdb
#share unopkg
%dir %{baseinstdir}/share/extensions
%{baseinstdir}/program/unopkg
%{baseinstdir}/program/unopkg.bin
%{baseinstdir}/program/bootstraprc
%{baseinstdir}/program/fundamentalrc
%{baseinstdir}/program/setuprc
%{baseinstdir}/program/intro.png
%{baseinstdir}/program/intro-highres.png
%{baseinstdir}/program/opencltest
%{baseinstdir}/program/soffice
%{baseinstdir}/program/soffice.bin
%{baseinstdir}/program/sofficerc
%{baseinstdir}/program/unoinfo
%{baseinstdir}/program/oosplash
%{baseinstdir}/program/shell/
%dir %{baseinstdir}/share/filter
%{baseinstdir}/share/filter/oox-drawingml-adj-names
%{baseinstdir}/share/filter/oox-drawingml-cs-presets
%{baseinstdir}/share/filter/signature-line.svg
%{baseinstdir}/share/filter/signature-line-draw.svg
%{baseinstdir}/share/filter/vml-shape-types
%{baseinstdir}/share/xdg/
%{baseinstdir}/program/redirectrc
%{_datadir}/applications/libreoffice-startcenter.desktop
#launchers
%{_bindir}/libreoffice
%{_bindir}/openoffice.org
%{_bindir}/soffice
%{_bindir}/ooffice
%{_bindir}/ooviewdoc
%{_mandir}/man1/libreoffice.1*
%{_mandir}/man1/openoffice.org.1*
%{_mandir}/man1/soffice.1*
%{_mandir}/man1/ooffice.1*
%{_mandir}/man1/ooviewdoc.1*

%files base
%ifarch %{java_arches}
%{baseinstdir}/program/classes/hsqldb.jar
%{baseinstdir}/program/classes/reportbuilder.jar
%{baseinstdir}/program/classes/reportbuilderwizard.jar
%{baseinstdir}/program/classes/sdbc_hsqldb.jar
%{baseinstdir}/program/classes/flow-engine.jar
%{baseinstdir}/program/classes/flute-*.jar
%{baseinstdir}/program/classes/libbase-*.jar
%{baseinstdir}/program/classes/libfonts-*.jar
%{baseinstdir}/program/classes/libformula-*.jar
%{baseinstdir}/program/classes/liblayout.jar
%{baseinstdir}/program/classes/libloader-*.jar
%{baseinstdir}/program/classes/librepository-*.jar
%{baseinstdir}/program/classes/libserializer-*.jar
%{baseinstdir}/program/classes/libxml-*.jar
%{baseinstdir}/program/classes/sac.jar
%endif
%{baseinstdir}/program/access2base.py
%{baseinstdir}/program/base.abignore
%{baseinstdir}/program/libabplo.so
%{baseinstdir}/program/libdbplo.so
%{baseinstdir}/program/libfirebird_sdbclo.so
%ifarch %{java_arches}
%{baseinstdir}/program/libhsqldb.so
%{baseinstdir}/program/librptlo.so
%{baseinstdir}/program/librptuilo.so
%{baseinstdir}/program/librptxmllo.so
%endif
%{baseinstdir}/share/registry/base.xcd
%ifarch %{java_arches}
%{baseinstdir}/share/registry/reportbuilder.xcd
%endif
%{baseinstdir}/program/sbase
%{_metainfodir}/libreoffice-base.appdata.xml
%{_datadir}/applications/libreoffice-base.desktop
%{_bindir}/oobase
%{_mandir}/man1/oobase.1*

%ifarch %{java_arches}

%files wiki-publisher
%docdir %{baseinstdir}/share/extensions/wiki-publisher/license
%{baseinstdir}/share/extensions/wiki-publisher

%files nlpsolver
%docdir %{baseinstdir}/share/extensions/nlpsolver/help
%{baseinstdir}/share/extensions/nlpsolver

%files officebean
%{baseinstdir}/program/classes/officebean.jar
%{baseinstdir}/program/officebean.abignore
%{baseinstdir}/program/libofficebean.so

%files officebean-common
%{_javadir}/%{name}/officebean.jar

%endif

%files ogltrans
%{baseinstdir}/program/ogltrans.abignore
%{baseinstdir}/program/libOGLTranslo.so
%{baseinstdir}/program/opengl/basicFragmentShader.glsl
%{baseinstdir}/program/opengl/basicVertexShader.glsl
%{baseinstdir}/program/opengl/dissolveFragmentShader.glsl
%{baseinstdir}/program/opengl/fadeBlackFragmentShader.glsl
%{baseinstdir}/program/opengl/fadeFragmentShader.glsl
%{baseinstdir}/program/opengl/glitterFragmentShader.glsl
%{baseinstdir}/program/opengl/glitterVertexShader.glsl
%{baseinstdir}/program/opengl/honeycombFragmentShader.glsl
%{baseinstdir}/program/opengl/honeycombGeometryShader.glsl
%{baseinstdir}/program/opengl/honeycombVertexShader.glsl
%{baseinstdir}/program/opengl/rippleFragmentShader.glsl
%{baseinstdir}/program/opengl/reflectionFragmentShader.glsl
%{baseinstdir}/program/opengl/reflectionVertexShader.glsl
%{baseinstdir}/program/opengl/staticFragmentShader.glsl
%{baseinstdir}/program/opengl/vortexFragmentShader.glsl
%{baseinstdir}/program/opengl/vortexGeometryShader.glsl
%{baseinstdir}/program/opengl/vortexVertexShader.glsl
%{baseinstdir}/share/config/soffice.cfg/simpress/transitions-ogl.xml
%{baseinstdir}/share/registry/ogltrans.xcd

%files pdfimport
%{baseinstdir}/program/pdfimport.abignore
%{baseinstdir}/program/libpdfimportlo.so
%{baseinstdir}/program/xpdfimport
%{baseinstdir}/share/registry/pdfimport.xcd
%{baseinstdir}/share/xpdfimport

%_font_pkg -n %{fontname} opens___.ttf
%doc LICENSE

%files calc
%{baseinstdir}/program/calc.abignore
%{baseinstdir}/program/libanalysislo.so
%{baseinstdir}/program/libcalclo.so
%{baseinstdir}/program/libdatelo.so
%{baseinstdir}/program/libpricinglo.so
%{baseinstdir}/program/libsclo.so
%{baseinstdir}/program/libscdlo.so
%{baseinstdir}/program/libscfiltlo.so
%{baseinstdir}/program/libscuilo.so
%{baseinstdir}/program/libsolverlo.so
%{baseinstdir}/program/libwpftcalclo.so
%{baseinstdir}/program/libvbaobjlo.so
%{baseinstdir}/share/calc/styles.xml
%{baseinstdir}/share/registry/calc.xcd
%{baseinstdir}/program/pagein-calc
%{baseinstdir}/program/scalc
%{_metainfodir}/libreoffice-calc.appdata.xml
%{_datadir}/applications/libreoffice-calc.desktop
%{_bindir}/oocalc
%{_mandir}/man1/oocalc.1*

%files draw
%{baseinstdir}/program/pagein-draw
%{baseinstdir}/program/sdraw
%{_metainfodir}/libreoffice-draw.appdata.xml
%{_datadir}/applications/libreoffice-draw.desktop
%{_bindir}/oodraw
%{_mandir}/man1/oodraw.1*

%files emailmerge
%{baseinstdir}/program/mailmerge.py*
%{baseinstdir}/program/msgbox.py*

%files writer
%{baseinstdir}/program/writer.abignore
%{baseinstdir}/program/libhwplo.so
%{baseinstdir}/program/liblwpftlo.so
%{baseinstdir}/program/libmswordlo.so
%{baseinstdir}/program/libswuilo.so
%{baseinstdir}/program/libt602filterlo.so
%{baseinstdir}/program/libwpftwriterlo.so
%{baseinstdir}/program/libwriterfilterlo.so
%{baseinstdir}/program/libwriterlo.so
%{baseinstdir}/program/libvbaswobjlo.so
%{baseinstdir}/share/registry/writer.xcd
%{baseinstdir}/program/pagein-writer
%{baseinstdir}/program/swriter
%{_metainfodir}/libreoffice-writer.appdata.xml
%{_datadir}/applications/libreoffice-writer.desktop
%{_bindir}/oowriter
%{_mandir}/man1/oowriter.1*

%files impress
%{baseinstdir}/program/impress.abignore
%{baseinstdir}/program/libPresentationMinimizerlo.so
%{baseinstdir}/program/libPresenterScreenlo.so
%{baseinstdir}/program/libwpftimpresslo.so
%dir %{baseinstdir}/share/config/soffice.cfg/simpress
%{baseinstdir}/share/config/soffice.cfg/simpress/effects.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/layoutlist.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/objectlist.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/styles.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/transitions.xml
%{baseinstdir}/share/registry/impress.xcd
%{baseinstdir}/program/pagein-impress
%{baseinstdir}/program/simpress
%{_metainfodir}/libreoffice-impress.appdata.xml
%{_datadir}/applications/libreoffice-impress.desktop
%{_bindir}/ooimpress
%{_mandir}/man1/ooimpress.1*

%files math
%{baseinstdir}/program/smath
%{_datadir}/applications/libreoffice-math.desktop
%{_bindir}/oomath
%{_mandir}/man1/oomath.1*

%files graphicfilter
%{baseinstdir}/program/graphicfilter.abignore
%{baseinstdir}/program/libgraphicfilterlo.so
%{baseinstdir}/program/libsvgfilterlo.so
%{baseinstdir}/program/libwpftdrawlo.so
%{baseinstdir}/share/registry/graphicfilter.xcd

%files xsltfilter
%{baseinstdir}/share/xslt
%{baseinstdir}/share/registry/xsltfilter.xcd
%{_datadir}/applications/libreoffice-xsltfilter.desktop

%files postgresql
%{baseinstdir}/program/postgresql.abignore
%{baseinstdir}/program/libpostgresql-sdbclo.so
%{baseinstdir}/program/libpostgresql-sdbc-impllo.so
%{baseinstdir}/program/services/postgresql-sdbc.rdb
%{baseinstdir}/share/registry/postgresql.xcd

%files ure
%ifarch %{java_arches}
%{baseinstdir}/program/classes/java_uno.jar
%{baseinstdir}/program/classes/juh.jar
%{baseinstdir}/program/classes/jurt.jar
%{baseinstdir}/program/classes/libreoffice.jar
%{baseinstdir}/program/classes/ridl.jar
%{baseinstdir}/program/classes/unoloader.jar
%{baseinstdir}/program/javaldx
%{baseinstdir}/program/javavendors.xml
%{baseinstdir}/program/jvmfwk3rc
%{baseinstdir}/program/JREProperties.class
%endif
%{baseinstdir}/program/ure.abignore
%{baseinstdir}/program/libaffine_uno_uno.so
%{baseinstdir}/program/libbinaryurplo.so
%{baseinstdir}/program/libbootstraplo.so
%{baseinstdir}/program/libgcc3_uno.so
%{baseinstdir}/program/libi18nlangtag.so
%{baseinstdir}/program/libintrospectionlo.so
%{baseinstdir}/program/libinvocadaptlo.so
%{baseinstdir}/program/libinvocationlo.so
%{baseinstdir}/program/libiolo.so
%ifarch %{java_arches}
%{baseinstdir}/program/libjava_uno.so
%{baseinstdir}/program/libjavaloaderlo.so
%{baseinstdir}/program/libjavavmlo.so
%{baseinstdir}/program/libjpipe.so
%{baseinstdir}/program/libjuh.so
%{baseinstdir}/program/libjuhx.so
%{baseinstdir}/program/libjvmaccesslo.so
%{baseinstdir}/program/libjvmfwklo.so
%endif
%{baseinstdir}/program/liblog_uno_uno.so
%{baseinstdir}/program/libnamingservicelo.so
%{baseinstdir}/program/libproxyfaclo.so
%{baseinstdir}/program/libreflectionlo.so
%{baseinstdir}/program/libreglo.so
%{baseinstdir}/program/libsal_textenclo.so
%{baseinstdir}/program/libstocserviceslo.so
%{baseinstdir}/program/libstorelo.so
%{baseinstdir}/program/libuno_cppu.so.3
%{baseinstdir}/program/libuno_cppuhelpergcc3.so.3
%{baseinstdir}/program/libuno_purpenvhelpergcc3.so.3
%{baseinstdir}/program/libuno_sal.so.3
%{baseinstdir}/program/libuno_salhelpergcc3.so.3
%{baseinstdir}/program/libunoidllo.so
%{baseinstdir}/program/libunsafe_uno_uno.so
%{baseinstdir}/program/libuuresolverlo.so
%{baseinstdir}/program/libxmlreaderlo.so
%{baseinstdir}/program/regview
%{baseinstdir}/program/services.rdb
%{baseinstdir}/program/types.rdb
%{baseinstdir}/program/uno
%{baseinstdir}/program/uno.bin
%{baseinstdir}/program/unorc

%files ure-common
%ifarch %{java_arches}
%dir %{_javadir}/%{name}
%{_javadir}/%{name}/juh.jar
%{_javadir}/%{name}/jurt.jar
%{_javadir}/%{name}/libreoffice.jar
%{_javadir}/%{name}/ridl.jar
%{_javadir}/%{name}/unoloader.jar
%endif
%license LICENSE

%files sdk
%{sdkinstdir}/
%exclude %{sdkinstdir}/docs/
%exclude %{sdkinstdir}/examples/

%files sdk-doc
%docdir %{sdkinstdir}/docs
%license LICENSE
%{sdkinstdir}/docs/
%{sdkinstdir}/examples/

%files pyuno
%{baseinstdir}/program/pyuno.abignore
%{baseinstdir}/program/libpyuno.so
%{baseinstdir}/program/pythonloader.py*
%{baseinstdir}/program/libpythonloaderlo.so
%{baseinstdir}/program/pythonloader.unorc
%{baseinstdir}/program/pythonscript.py*
%{baseinstdir}/program/pyuno.so
%{baseinstdir}/program/scriptforge.py*
%{baseinstdir}/program/services/pyuno.rdb
%{baseinstdir}/program/services/scriptproviderforpython.rdb
%{baseinstdir}/program/wizards
%{baseinstdir}/share/Scripts/python
%exclude %{baseinstdir}/share/Scripts/python/LibreLogo
%{baseinstdir}/program/uno.py*
%{baseinstdir}/program/unohelper.py*
%{baseinstdir}/program/officehelper.py*
%{baseinstdir}/share/registry/pyuno.xcd
%{baseinstdir}/program/python
%{baseinstdir}/program/python.bin
%{baseinstdir}/program/python-core-*

%files librelogo
%{baseinstdir}/share/registry/librelogo.xcd
%{baseinstdir}/share/Scripts/python/LibreLogo

%files glade
%{_datadir}/glade
%{_datadir}/glade3

%files data
%{_datadir}/icons/hicolor/*/*/libreoffice*
%{_datadir}/mime/packages/libreoffice.xml
%ifarch %{java_arches}
%dir %{_javadir}/%{name}
%{_javadir}/%{name}/unoil.jar
%endif
%dir %{datadir}
%doc CREDITS.fodt
%doc LICENSE.html
%doc LICENSE
%doc NOTICE
%license LICENSE

%files x11
%{baseinstdir}/program/x11.abignore
%{baseinstdir}/program/libvclplug_genlo.so

%files gtk3
%{baseinstdir}/program/gtk3.abignore
%{baseinstdir}/program/libvclplug_gtk3lo.so

%if 0
%files gtk4
%{baseinstdir}/program/gtk4.abignore
%{baseinstdir}/program/libvclplug_gtk4lo.so
%endif

%files kf5
%{baseinstdir}/program/kf5.abignore
%{baseinstdir}/program/libkf5be1lo.so
%{baseinstdir}/program/libvclplug_gtk3_kde5lo.so
%{baseinstdir}/program/libvclplug_kf5lo.so
%{baseinstdir}/program/libvclplug_qt5lo.so
%{baseinstdir}/program/lo_kde5filepicker
%{_metainfodir}/org.libreoffice.kde.metainfo.xml

%files -n libreofficekit
%{baseinstdir}/share/libreofficekit
%{baseinstdir}/program/libreofficekit.abignore
%{baseinstdir}/program/liblibreofficekitgtk.so


%changelog
* Tue Jun 06 2023 Phantom X <megaphantomx at hotmail dot com> - 2:7.5.3.2-100
- Initial spec
