#!/usr/bin/bash
# -- winedxvkcfg --
# Sets wine Gallium Nine dll redirection.
#
# Script by Phantom X <megaphantomx at bol.com.b>
# Suggested usage: $ wineninecfg --help
#
# Copyright 2018-2020 Phantom X, Goiania, Brazil.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR `AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

ver=20200411

name="Gallium Nine"
pkgname="wine-nine"
dllsuffix="-nine"
dlls="d3d9"
nodlls="dxgi"

unset winebits
enabled=0
enabledlnk=0
disabled=0
disabledlnk=0
dllmissing=0
retval=0
overrideskey="HKCU\\Software\\Wine\\DllOverrides"

txt() {
cat <<EOF
$(basename "$0")
Uso : $0 <option>
-c|--check        Check ${name} dll redirection settings.
-s|1|--set        Enable ${name} dll redirection.
-u|0|--unset      Disable ${name} dll redirection.
-V|--version      Show version.
-h|--help         Show this message.
EOF
}

checkcfg(){
  for winebits in 64 32 ;do
    if [ "${winebits}" -eq 64 ] ;then
      lib=64
    else
      lib=''
    fi
    native_path="$(wine${winebits} winepath -u 'C:\windows\system32' 2>/dev/null | tr -d '\r')"
    lib_path="/usr/lib${lib}/wine"
    for dll in ${dlls} ;do
      if wine${winebits} reg query "${overrideskey}" /v "${dll}" 2>/dev/null | grep -q -F "native" ;then
        enabled=1
      else
        disabled=1
      fi
    done
    if [ -f "${native_path}/${dll}.dll" ] && [ "$(readlink -f "${lib_path}/${dll}${dllsuffix}.dll.so")" == "$(readlink -f "${native_path}/${dll}.dll")" ] ;then
      enabledlnk=1
    else
      disabledlnk=1
    fi
  done

  if [ "${enabled}" -eq 1 ] && [ "${disabled}" -eq 0 ] && [ "${enabledlnk}" -eq 1 ] && [ "${disabledlnk}" -eq 0 ] ;then
    echo "${name} is enabled!"
  elif [ "${enabled}" -eq 1 ] && [ "${disabled}" -eq 1 ] || [ "${enabledlnk}" -eq 1 ] && [ "${disabledlnk}" -eq 1 ] ;then
    echo "${name} settings are corrupted!"
    echo "Rerun with --set or --unset to fix!"
  else
    echo "${name} is not enabled!"
  fi
  exit 0
}

setcfg(){
  enabled=1
  for winebits in 64 32 ;do
    if [ "${winebits}" -eq 64 ] ;then
      lib=64
    else
      lib=''
    fi
    if wine${winebits} reg query /? &>/dev/null ;then
      native_path="$(wine${winebits} winepath -u 'C:\windows\system32' 2>/dev/null | tr -d '\r')"
      lib_path="/usr/lib${lib}/wine"
      for dll in ${dlls} ;do
        if ! [ -f "${lib_path}/${dll}${dllsuffix}.dll.so" ];then
          echo "Missing ${dll}${dllsuffix}.dll in /usr/lib${lib}/wine/."
          dllmissing=1
        fi
      done
      if [ "${dllmissing}" -eq 1 ] ;then
        continue
      fi
      if [ -n "${nodlls}" ] ;then
        for nodll in ${nodlls} ;do
          if wine${winebits} reg query "${overrideskey}" /v "${nodll}" &>/dev/null ;then
            wine${winebits} reg delete "${overrideskey}" /v "${nodll}" /f &>/dev/null
            retval=$?
          fi
        done
      fi
      for dll in ${dlls} ;do
        wine${winebits} reg add "${overrideskey}" /v "${dll}" -t REG_SZ /d native /f &>/dev/null
        retval=$?
        if [ "${retval}" -eq 0 ] ;then
          enabled=1
        else
          disabled=1
        fi
        ln -sf "${lib_path}/${dll}${dllsuffix}.dll.so" "${native_path}/${dll}.dll"
        retval=$?
        if [ "${retval}" -eq 0 ] ;then
          enabledlnk=1
        else
          enabledlnk=0
        fi
      done
    fi
  done
  if [ "${dllmissing}" -eq 1 ] ;then
    echo "Reinstall ${pkgname}."
    exit 1
  fi
  if [ "${enabled}" -eq 1 ] && [ "${disabled}" -eq 0 ] && [ "${enabledlnk}" -eq 1 ] ;then
    echo "${name} is enabled!"
  else
    echo "${name} configuration fail!"
    echo "Check wine prefix or permissions."
    exit 1
  fi
  exit $?
}

unsetcfg(){
  disabled=1
  disabledlnk=1
  for winebits in 64 32 ;do
    if [ "${winebits}" -eq 64 ] ;then
      lib=64
    else
      lib=''
    fi
    if wine${winebits} reg query /? &>/dev/null ;then
      native_path="$(wine${winebits} winepath -u 'C:\windows\system32' 2>/dev/null)"
      lib_path="/usr/lib${lib}/wine"
      for dll in ${dlls} ;do
        if wine${winebits} reg query "${overrideskey}" /v "${dll}" 2>/dev/null | grep -q -F "native" &>/dev/null ;then
          wine${winebits} reg delete "${overrideskey}" /v "${dll}" /f &>/dev/null
          retval=$?
          if [ "${retval}" -eq 0 ] ;then
            disabled=1
          else
            disabled=0
          fi
        fi
        if [ -f "${native_path}/${dll}.dll" ] && [ "$(readlink -f "${lib_path}/${dll}${dllsuffix}.dll.so")" == "$(readlink -f "${native_path}/${dll}.dll")" ] ;then
          rm -f "${native_path}/${dll}.dll"
          retval=$?
          if [ "${retval}" -eq 0 ] ;then
            disabledlnk=1
          else
            disabledlnk=0
          fi
        fi
      done
    fi
  done
  if [ "${disabled}" -eq 1 ] && [ "${disabledlnk}" -eq 1 ] ;then
    echo "${name} is disabled!"
  else
    echo "${name} configuration fail!"
    echo "Check wine prefix or permissions."
    exit 1
  fi
  exit $?
}

if [ -z "$1" ] ;then
  txt
  exit 0
fi

while [ -n "$1" ] ;do
  case "$1" in
    -h|--help)
      txt
      exit 0
      ;;
    -V|--version)
      echo "${ver}"
      exit 0
      ;;
    -c|--check)
      checkcfg
      ;;
    -s|1|--set|--enable|--on)
      setcfg
      ;;
    -u|0|--unset|--disable|--off)
      unsetcfg
      ;;
    -*)
      echo "$0: unrecognized option '$1'"
      echo "Try '$0 --help' for more information."
      exit 2
      ;;
  esac
  shift
done
